### ISSUE TITLE
.exe version of the converter

### ISSUE THREAD

**Issue by ahmadmud** [BuXXe/PARAM.PFD-PS3-Demons-Souls-Savegame-Tool#1]
Hello BuXXe,

I am seeking your help as I unfortunately have zero experience using python.

Do you mind creating an exe version of this converter, your tool is extremely useful and one I have been searching for.
Would highly appreciate if you have time to do so.

Many thanks!

**Comment by BuXXe** [comment]
First off, thank you for your interest. 
On to the topic: The converter does not have any kind of User Interface. It is meant to be used by programmers / advanced users rather than end users. Furthermore, there are some approaches of converting python programs to .exe but they are not working pretty good.
So unfortunately i have to advice you to download python 2.7 install it and install the dependency i mentioned in the readme. You need to have some hex editor skills anyway to really work with this thing.
